title: Gearbox Embedded Systems Training
description: Self documenting embedded systems webpage
theme: just-the-docs
color_scheme: dark

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default

just_the_docs:
  search_enabled: true
  aux_links:
    "View on GitHub":
      - "https://github.com/KimeuDom/KimeuDom-GearBox-Academy"
