name: Build and Deploy Jekyll to /docs

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # or latest compatible version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Commit & push to /docs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "dom@github-actions[bot]"
          git config user.email "kimeudom.git@gmail.com"
          git add docs
          git commit -m "Auto-update GitHub Pages site [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:master
